[tox]
requires =
    tox>=4.2
env_list =
    clean
    py3{10-14}-{opentelemetry-instrumentation-asyncfast}
    py3{10-14}-{opentelemetry-instrumentation-asyncfast}-import

[testenv]
runner = uv-venv-lock-runner
description = run the tests with pytest
commands =
    pytest {tty:--color=yes} {posargs:-v --cov --cov-append --cov-report=xml}
depends =
    {py314, py313, py312, py311, py310}: clean
uv_sync_flags = --all-packages

[testenv:clean]
description = clean coverage report
commands =
    coverage erase
uv_sync_flags = --all-packages

[testenv:py3{10-14}-opentelemetry-instrumentation-asyncfast]
commands =
    {[testenv]commands} packages/opentelemetry-instrumentation-asyncfast
uv_sync_flags = --package=opentelemetry-instrumentation-asyncfast

[testenv:py3{10-14}-opentelemetry-instrumentation-asyncfast-import]
commands =
    python -c "import opentelemetry.instrumentation.asyncfast"
uv_sync_flags =
    --package=opentelemetry-instrumentation-asyncfast
    --no-dev
